# Generated by Django 3.2.23 on 2023-11-22 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ghadi',
            name='name',
        ),
        migrations.AddField(
            model_name='ghadi',
            name='ds',
            field=models.CharField(default='Not declared', max_length=255),
        ),
        migrations.AddField(
            model_name='ghadi',
            name='fb',
            field=models.CharField(default='Not declared', max_length=255),
        ),
        migrations.AddField(
            model_name='ghadi',
            name='gali',
            field=models.CharField(default='Not declared', max_length=255),
        ),
        migrations.AddField(
            model_name='ghadi',
            name='gb',
            field=models.CharField(default='Not declared', max_length=255),
        ),
        migrations.AddField(
            model_name='ghadi',
            name='sg',
            field=models.CharField(default='Not declared', max_length=255),
        ),
        migrations.AlterField(
            model_name='ghadi',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
