# Generated by Django 3.2.23 on 2023-11-30 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0002_auto_20231122_2154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ghadi',
            old_name='ds',
            new_name='dl',
        ),
        migrations.RenameField(
            model_name='ghadi',
            old_name='gali',
            new_name='nazi',
        ),
        migrations.RenameField(
            model_name='ghadi',
            old_name='sg',
            new_name='sn',
        ),
    ]
