# Generated by Django 3.2.23 on 2023-12-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0003_auto_20231130_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghadi',
            name='dl',
            field=models.CharField(default='Wait', max_length=255),
        ),
        migrations.AlterField(
            model_name='ghadi',
            name='fb',
            field=models.CharField(default='Wait', max_length=255),
        ),
        migrations.AlterField(
            model_name='ghadi',
            name='gb',
            field=models.CharField(default='Wait', max_length=255),
        ),
        migrations.AlterField(
            model_name='ghadi',
            name='nazi',
            field=models.CharField(default='Wait', max_length=255),
        ),
        migrations.AlterField(
            model_name='ghadi',
            name='sn',
            field=models.CharField(default='Wait', max_length=255),
        ),
    ]
